#!/bin/sh
# Regenerates the TypeScript protocol bindings from ../../remote-agent/crates/protocol (ts-rs)
# and copies them into src/protocol/. The copies are committed so the web app builds standalone.
set -eu
HERE="$(cd "$(dirname "$0")/.." && pwd)"
AGENT_REPO="${AGENT_REPO:-$HERE/../../remote-agent}"
if [ ! -d "$AGENT_REPO/crates/protocol" ]; then
  echo "remote-agent checkout not found at $AGENT_REPO (set AGENT_REPO)" >&2
  exit 1
fi
( cd "$AGENT_REPO" && cargo test -p protocol --quiet )
OUT="$HERE/src/protocol"
mkdir -p "$OUT"
find "$OUT" -name '*.ts' ! -name 'index.ts' -delete
cp "$AGENT_REPO"/crates/protocol/bindings/*.ts "$OUT"/
# barrel
{
  echo "// Generated by scripts/sync-protocol.sh — do not edit by hand."
  for f in "$OUT"/*.ts; do
    n="$(basename "$f" .ts)"
    [ "$n" = "index" ] && continue
    echo "export type { $n } from './$n';"
  done
} > "$OUT/index.ts"
echo "synced $(ls "$OUT" | grep -c '\.ts$') protocol files into src/protocol/"
