// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayInfo } from "./DisplayInfo";
import type { VideoCodec } from "./VideoCodec";

/**
 * What an agent can do, reported in `hello` and whenever it changes.
 */
export type AgentCapabilities = { 
/**
 * Codecs the agent can *encode*, best first (hardware H265 → hardware H264 → software H264).
 */
codecs: Array<VideoCodec>, displays: Array<DisplayInfo>, input: boolean, clipboard: boolean, };
