// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceMode } from "./DeviceMode";
import type { IceServer } from "./IceServer";
import type { VideoCodec } from "./VideoCodec";

/**
 * Runtime configuration of an agent. Owned by the console, pushed to the agent in
 * `hello_ack` and `config_update`, and cached on disk by the agent so it can start
 * while the console is unreachable.
 */
export type AgentConfig = { 
/**
 * Human readable name shown in the console (defaults to hostname).
 */
display_name: string, mode: DeviceMode, 
/**
 * Seconds between heartbeats.
 */
heartbeat_interval_s: number, 
/**
 * STUN/TURN servers to use for sessions (may be overridden per session).
 */
ice_servers: Array<IceServer>, 
/**
 * Upper bound for capture/encode frame rate.
 */
max_fps: number, 
/**
 * Encoder target bitrate in kbit/s.
 */
max_bitrate_kbps: number, 
/**
 * Codec to prefer when both sides support it.
 */
preferred_codec: VideoCodec, 
/**
 * Whether operators are allowed to inject mouse/keyboard input.
 */
allow_input: boolean, 
/**
 * Whether clipboard sync is allowed.
 */
allow_clipboard: boolean, 
/**
 * Help-me mode: seconds the approval prompt stays open before auto-deny.
 */
approval_timeout_s: number, 
/**
 * Whether operators may send/receive files and browse the device file system.
 */
allow_file_transfer: boolean, 
/**
 * Directory that receives uploads (default: `<home>/Downloads/RemoteAgent`).
 */
transfer_dir?: string, 
/**
 * Whether system audio may be streamed to the operator.
 */
allow_audio: boolean, };
