// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentCapabilities } from "./AgentCapabilities";
import type { Arch } from "./Arch";
import type { DeviceMode } from "./DeviceMode";
import type { DisplayInfo } from "./DisplayInfo";
import type { EndReason } from "./EndReason";
import type { IceCandidate } from "./IceCandidate";
import type { LocalOverrides } from "./LocalOverrides";
import type { Os } from "./Os";
import type { SessionDescription } from "./SessionDescription";
import type { SessionEvent } from "./SessionEvent";
import type { SessionState } from "./SessionState";
import type { VideoCodec } from "./VideoCodec";

export type AgentToConsole = { "type": "hello", protocol_version: number, device_id: string, device_secret: string, agent_version: string, hostname: string, os: Os, arch: Arch, 
/**
 * Mode the agent is currently running with (from its cached config).
 */
mode: DeviceMode, capabilities: AgentCapabilities, 
/**
 * User currently logged in at the console session, if known.
 */
logged_in_user?: string, 
/**
 * Restrictions set locally by the person at the device.
 */
local_overrides?: LocalOverrides, } | { "type": "heartbeat", uptime_s: bigint, logged_in_user?: string, cpu_percent?: number, mem_percent?: number, 
/**
 * Present only when displays changed since the last report.
 */
displays?: Array<DisplayInfo>, 
/**
 * Present only when the local restrictions changed since the last report.
 */
local_overrides?: LocalOverrides, } | { "type": "approval_result", session_id: string, approved: boolean, } | { "type": "session_answer", session_id: string, answer: SessionDescription, 
/**
 * Codec the agent will encode with after negotiation.
 */
codec: VideoCodec, } | { "type": "ice_candidate", session_id: string, candidate: IceCandidate, } | { "type": "session_state", session_id: string, state: SessionState, reason?: EndReason, } | { "type": "session_event", session_id: string, event: SessionEvent, 
/**
 * Unix epoch milliseconds (agent clock).
 */
ts_ms: bigint, } | { "type": "pong", nonce: bigint, } | { "type": "log", level: string, message: string, };
