// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BakedConfig } from "./BakedConfig";

/**
 * Signed envelope stored in the trailer.
 */
export type BakedPayload = { config: BakedConfig, 
/**
 * Console ed25519 public key, base64 (32 bytes).
 */
public_key: string, 
/**
 * ed25519 signature over [`canonical_json`] of `config`, base64 (64 bytes).
 */
signature: string, };
