// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Branding } from "./Branding";

/**
 * What a baked binary knows about its console.
 */
export type BakedConfig = { version: number, 
/**
 * Console base URL, e.g. `https://remote.example.com`.
 */
server_url: string, 
/**
 * Enrollment token to use automatically (long-lived install tokens or one-off quick-support tokens).
 */
enroll_token?: string, 
/**
 * Quick-support build: run in the foreground as a temporary device, offer "Install as service".
 */
quick_support: boolean, branding: Branding, 
/**
 * Unix epoch seconds when the trailer was produced.
 */
issued_at: bigint, };
