// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Branding shown by the agent application window, banner and approval dialog.
 */
export type Branding = { 
/**
 * Product name, e.g. "Acme Remote Support".
 */
product_name: string, 
/**
 * Accent colour as `#rrggbb`.
 */
accent: string, 
/**
 * PNG logo, base64 (≤ 512 KiB decoded), optional.
 */
logo_png_base64?: string, 
/**
 * Short text shown to the person at the device ("Support by Acme IT, +49 …").
 */
support_text: string, 
/**
 * Organisation name shown in the About section.
 */
organization: string, };
