// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentConfig } from "./AgentConfig";
import type { EndReason } from "./EndReason";
import type { IceCandidate } from "./IceCandidate";
import type { IceServer } from "./IceServer";
import type { OperatorInfo } from "./OperatorInfo";
import type { SessionDescription } from "./SessionDescription";

export type ConsoleToAgent = { "type": "hello_ack", protocol_version: number, 
/**
 * Unix epoch milliseconds on the console; used for clock-skew estimates only.
 */
server_time_ms: bigint, config: AgentConfig, } | { "type": "config_update", config: AgentConfig, } | { "type": "session_request", session_id: string, operator: OperatorInfo, offer: SessionDescription, 
/**
 * ICE servers for this session (includes short-lived TURN credentials).
 */
ice_servers: Array<IceServer>, } | { "type": "ice_candidate", session_id: string, candidate: IceCandidate, } | { "type": "session_end", session_id: string, reason: EndReason, } | { "type": "ping", nonce: bigint, } | { "type": "update", version: string, url: string, sha256: string, } | { "type": "goodbye", reason: string, };
