// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatParty } from "./ChatParty";
import type { ClipboardKind } from "./ClipboardKind";
import type { DisplayInfo } from "./DisplayInfo";
import type { VideoCodec } from "./VideoCodec";

export type ControlMessage = { "t": "select_display", index: number, } | { "t": "set_active_displays", indices: Array<number>, } | { "t": "set_audio", enabled: boolean, } | { "t": "chat", from: ChatParty, text: string, 
/**
 * Unix epoch milliseconds.
 */
ts_ms: bigint, } | { "t": "set_quality", max_fps?: number, max_bitrate_kbps?: number, } | { "t": "request_keyframe" } | { "t": "secure_attention" } | { "t": "clipboard_set", text: string, } | { "t": "display_info", displays: Array<DisplayInfo>, 
/**
 * Primary display (the one `select_display` targets).
 */
current: number, 
/**
 * Displays currently being streamed (see `set_active_displays`).
 */
active: Array<number>, 
/**
 * Whether an audio track is available on this session.
 */
audio: boolean, } | { "t": "clipboard_available", kind: ClipboardKind, 
/**
 * File names (or a single generated name for images).
 */
names: Array<string>, total_bytes: bigint, } | { "t": "clipboard_changed", text: string, } | { "t": "stats", display: number, codec: VideoCodec, fps: number, bitrate_kbps: number, width: number, height: number, 
/**
 * Capture→encode→send latency estimate in milliseconds.
 */
pipeline_ms: number, hardware: boolean, } | { "t": "session_ended_by_user" } | { "t": "observer_joined", name: string, } | { "t": "observer_left", name: string, } | { "t": "control_paused", paused: boolean, };
