// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatParty } from "./ChatParty";
import type { ClipboardKind } from "./ClipboardKind";
import type { DisplayInfo } from "./DisplayInfo";
import type { VideoCodec } from "./VideoCodec";

export type ControlMessage = { "t": "select_display", index: number, } | { "t": "set_active_displays", indices: Array<number>, } | { "t": "set_audio", enabled: boolean, } | { "t": "chat", from: ChatParty, text: string, 
/**
 * Unix epoch milliseconds.
 */
ts_ms: bigint, } | { "t": "set_quality", max_fps?: number, max_bitrate_kbps?: number, } | { "t": "request_keyframe" } | { "t": "secure_attention" } | { "t": "clipboard_set", text: string, } | { "t": "display_info", displays: Array<DisplayInfo>, 
/**
 * Primary display (the one `select_display` targets).
 */
current: number, 
/**
 * Displays currently being streamed (see `set_active_displays`).
 */
active: Array<number>, 
/**
 * Whether an audio track is available on this session.
 */
audio: boolean, } | { "t": "clipboard_available", kind: ClipboardKind, 
/**
 * File names (or a single generated name for images).
 */
names: Array<string>, total_bytes: bigint, } | { "t": "clipboard_changed", text: string, } | { "t": "stats", display: number, codec: VideoCodec, 
/**
 * Encoded picture size (may be smaller than the display when viewport scaling is on).
 */
encoded_width: number, encoded_height: number, 
/**
 * Capture → encoded latency and encode duration, milliseconds (averages over the window).
 */
capture_to_encoded_ms: number, encode_ms: number, 
/**
 * Keyframes sent in the window and current GOP policy (0 = keyframes only on demand).
 */
keyframes: number, frames_skipped_idle: number, fps: number, bitrate_kbps: number, width: number, height: number, 
/**
 * Capture→encode→send latency estimate in milliseconds.
 */
pipeline_ms: number, hardware: boolean, } | { "t": "session_ended_by_user" } | { "t": "observer_joined", name: string, } | { "t": "observer_left", name: string, } | { "t": "control_paused", paused: boolean, } | { "t": "annotate_stroke", id: number, display: number, color: string, 
/**
 * Width in physical pixels.
 */
width: number, points: Array<[number, number]>, } | { "t": "annotate_end", id: number, } | { "t": "annotate_pointer", display: number, point?: [number, number], color: string, } | { "t": "annotate_clear" } | { "t": "annotations_disabled" } | { "t": "set_viewport", display: number, width?: number, height?: number, } | { "t": "cursor_shape", id: number, png_base64: string, hotspot_x: number, hotspot_y: number, width: number, height: number, } | { "t": "cursor_position", display: number, x: number, y: number, shape_id: number, visible: boolean, };
