// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayInfo } from "./DisplayInfo";
import type { VideoCodec } from "./VideoCodec";

export type ControlMessage = { "t": "select_display", index: number, } | { "t": "set_quality", max_fps?: number, max_bitrate_kbps?: number, } | { "t": "request_keyframe" } | { "t": "secure_attention" } | { "t": "clipboard_set", text: string, } | { "t": "display_info", displays: Array<DisplayInfo>, current: number, } | { "t": "clipboard_changed", text: string, } | { "t": "stats", codec: VideoCodec, fps: number, bitrate_kbps: number, width: number, height: number, 
/**
 * Capture→encode→send latency estimate in milliseconds.
 */
pipeline_ms: number, hardware: boolean, } | { "t": "session_ended_by_user" };
