// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Arch } from "./Arch";
import type { DeviceMode } from "./DeviceMode";
import type { DisplayInfo } from "./DisplayInfo";
import type { Os } from "./Os";
import type { VideoCodec } from "./VideoCodec";

/**
 * Device row as shown in the console; also the payload of live updates.
 */
export type DeviceSummary = { id: string, name: string, hostname: string, os: Os, arch: Arch, agent_version: string, mode: DeviceMode, tags: Array<string>, online: boolean, 
/**
 * ISO-8601 timestamp of last heartbeat / disconnect.
 */
last_seen_at?: string, logged_in_user?: string, last_ip?: string, codecs: Array<VideoCodec>, displays: Array<DisplayInfo>, 
/**
 * Id of the active session, if any.
 */
active_session_id?: string, };
