// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The calling user's effective permission on a device (admins always `manage`).
 */
export type DevicePermission = "view" | "connect" | "manage";
