// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A physical display attached to the device, in the device's global coordinate space.
 */
export type DisplayInfo = { 
/**
 * Stable index used by [`crate::channel::ControlMessage::SelectDisplay`].
 */
index: number, name: string, 
/**
 * Origin in global (virtual desktop) logical coordinates.
 */
x: number, y: number, 
/**
 * Size in physical pixels (the size of the captured/encoded video).
 */
width: number, height: number, 
/**
 * Backing scale factor (2.0 on Retina). Logical size = physical / scale.
 */
scale: number, primary: boolean, };
