// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a session ended.
 */
export type EndReason = "operator_closed" | "device_user_closed" | "denied" | "approval_timeout" | "agent_offline" | "connection_failed" | "error";
