// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Arch } from "./Arch";
import type { Os } from "./Os";

/**
 * Body of `POST /api/enroll` sent by a freshly installed agent.
 */
export type EnrollRequest = { 
/**
 * One-time / limited-use enrollment token issued by the console.
 */
token: string, hostname: string, os: Os, arch: Arch, agent_version: string, 
/**
 * Optional operator-facing name (`remote-agent enroll --name`); defaults to the hostname.
 */
display_name?: string, };
