// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentConfig } from "./AgentConfig";

/**
 * Response of `POST /api/enroll`.
 */
export type EnrollResponse = { device_id: string, 
/**
 * Long-lived secret the agent authenticates with on `/ws/agent`. Shown once.
 */
device_secret: string, 
/**
 * Canonical console base URL the agent should use from now on.
 */
server_url: string, config: AgentConfig, };
