// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Directory listing entry.
 */
export type FileEntry = { name: string, is_dir: boolean, size: bigint, 
/**
 * Unix epoch milliseconds.
 */
modified_ms?: bigint, hidden: boolean, };
