// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Directory listing entry.
 */
export type FileEntry = { name: string, is_dir: boolean, size: bigint, 
/**
 * Unix epoch milliseconds.
 */
modified_ms?: bigint, hidden: boolean, 
/**
 * Absolute path of the entry. Set for the well-known roots returned by `list { path: None }`
 * (where `name` is a display label such as "Home"); regular listings leave it `None`
 * and clients join `Listing.path` with `name`.
 */
path?: string, };
