// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileEntry } from "./FileEntry";
import type { TransferDirection } from "./TransferDirection";
import type { TransferKind } from "./TransferKind";

export type FileMessage = { "t": "offer", transfer_id: number, token: string, name: string, size: bigint, kind: TransferKind, direction: TransferDirection, 
/**
 * Device directory to store into (`ToDevice`, `File` only); default transfer dir.
 */
dest_dir?: string, 
/**
 * Ties the files of one clipboard file list together.
 */
group?: string, 
/**
 * Known up front when the sender already hashed the file (optional; `complete` always carries it).
 */
sha256?: string, } | { "t": "accept", transfer_id: number, 
/**
 * Bytes the receiver already has (resume point).
 */
offset: bigint, } | { "t": "reject", transfer_id: number, reason: string, } | { "t": "ack", transfer_id: number, offset: bigint, } | { "t": "complete", transfer_id: number, sha256: string, } | { "t": "done", transfer_id: number, ok: boolean, error?: string, 
/**
 * Final path on the device (`ToDevice`).
 */
path?: string, } | { "t": "cancel", transfer_id: number, reason: string, } | { "t": "request", transfer_id: number, path: string, } | { "t": "list", path?: string, } | { "t": "listing", path: string, entries: Array<FileEntry>, error?: string, } | { "t": "mkdir", path: string, } | { "t": "delete", path: string, } | { "t": "rename", from: string, to: string, } | { "t": "op_result", op: string, path: string, ok: boolean, error?: string, } | { "t": "request_clipboard" } | { "t": "clipboard_group_complete", group: string, };
