// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A device group the current user can see.
 */
export type GroupRef = { id: string, name: string, };
