// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ICE server entry as passed to `RTCPeerConnection` / webrtc-rs.
 */
export type IceServer = { urls: Array<string>, username?: string, credential?: string, };
