// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MouseButton } from "./MouseButton";

export type InputEvent = { "t": "mm", x: number, y: number, } | { "t": "md", button: MouseButton, } | { "t": "mu", button: MouseButton, } | { "t": "mw", dx: number, dy: number, } | { "t": "kd", code: string, } | { "t": "ku", code: string, } | { "t": "tx", text: string, } | { "t": "rel" };
