// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceMode } from "./DeviceMode";

/**
 * Restrictions the person at the device applies locally in the agent app. They can only
 * **tighten** the console's [`AgentConfig`] (require approval, block input/audio/clipboard/
 * files); `None` = follow the console. Reported to the console so admins see the effective
 * policy.
 */
export type LocalOverrides = { 
/**
 * `Some(HelpMe)` forces approval even when the console says unattended (`Some(Unattended)`
 * is ignored — it cannot loosen policy).
 */
mode?: DeviceMode, allow_input?: boolean, allow_audio?: boolean, allow_clipboard?: boolean, allow_file_transfer?: boolean, allow_annotations?: boolean, };
