// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Minimal description of the operator shown to the person at the device.
 */
export type OperatorInfo = { id: string, name: string, };
