// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How completely a device can hide its own displays while an operator works (the
 * "privacy screen"). Reported in `hello` capabilities; the viewer only offers the control
 * when it is not `Unsupported`.
 */
export type PrivacyScreenSupport = "unsupported" | "screen_only" | "standard";
