// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who or what changed the privacy screen, or why a request was refused.
 */
export type PrivacyScreenReason = "operator" | "device_user" | "policy" | "permission" | "unsupported" | "locked" | "timeout" | "watchdog" | "displays_changed" | "control_paused" | "session_ended" | "failed";
