// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatParty } from "./ChatParty";
import type { OperatorInfo } from "./OperatorInfo";
import type { PrivacyScreenReason } from "./PrivacyScreenReason";
import type { TransferDirection } from "./TransferDirection";
import type { TransferKind } from "./TransferKind";

/**
 * Something noteworthy that happened inside a session; persisted by the console
 * (`GET /api/sessions/:id/events`) and pushed to UIs as `ConsoleToUi::SessionEvent`.
 */
export type SessionEvent = { "type": "chat", from: ChatParty, text: string, } | { "type": "transfer_started", token: string, name: string, size: bigint, kind: TransferKind, direction: TransferDirection, 
/**
 * Resume offset (0 for a fresh transfer).
 */
offset: bigint, } | { "type": "transfer_completed", token: string, name: string, size: bigint, direction: TransferDirection, path?: string, } | { "type": "transfer_failed", token: string, name: string, reason: string, } | { "type": "clipboard_sync", direction: TransferDirection, summary: string, } | { "type": "displays_changed", active: Array<number>, } | { "type": "audio_changed", enabled: boolean, } | { "type": "observer_joined", observer: OperatorInfo, session_id: string, } | { "type": "observer_left", observer: OperatorInfo, session_id: string, } | { "type": "control_paused", paused: boolean, } | { "type": "privacy_screen", active: boolean, reason: PrivacyScreenReason, };
