// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndReason } from "./EndReason";
import type { SessionState } from "./SessionState";
import type { VideoCodec } from "./VideoCodec";

/**
 * Session row as shown in the console.
 */
export type SessionSummary = { id: string, device_id: string, device_name: string, operator_id: string, operator_name: string, state: SessionState, started_at: string, connected_at?: string, ended_at?: string, end_reason?: EndReason, codec?: VideoCodec, };
