// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State machine of a remote session as tracked by the console.
 */
export type SessionState = "requested" | "awaiting_approval" | "connecting" | "connected" | "ended";
