// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session-level SDP description (mirrors `RTCSessionDescriptionInit`).
 */
export type SessionDescription = { 
/**
 * `"offer"` or `"answer"`.
 */
type: string, sdp: string, };
