// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IceCandidate } from "./IceCandidate";
import type { SessionDescription } from "./SessionDescription";

export type UiToConsole = { "type": "session_offer", device_id: string, offer: SessionDescription, 
/**
 * Admins only: shadow this running session instead of starting a new one.
 */
shadow_of?: string, } | { "type": "ice_candidate", session_id: string, candidate: IceCandidate, } | { "type": "session_end", session_id: string, } | { "type": "subscribe" } | { "type": "ping", nonce: bigint, };
