// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Video codec used on the WebRTC video track.
 */
export type VideoCodec = "h265" | "h264";
